---
title: "SR-Aging_brain-plots"
author: "Cooper Joseph Sharp"
date: "2025-12-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.width = 6, fig.height = 6)
```

## 1. Load Libraries

```{r libraries}
packages <- c(
  "dplyr",
  "ggplot2",
  "correlation",
  "readr",
  "tidyverse",
  "MASS",
  "ggeffects",
  "insight",
  "interactions"
)

# Install missing packages
installed <- rownames(installed.packages())
for (pkg in packages) {
  if (!pkg %in% installed) {
    install.packages(pkg)
  }
}

# Load packages
lapply(packages, library, character.only = TRUE)

```

## 2. Data Import and Preparation

```{r}

## Here is a list of the columns in the spreadsheet, and which covariates they should show results for:

# mask-rsfg_type-nppi_cnum-10_cname-rew-pun (Age X Ratings Interaction Positive; slide 85)
# mask-dlpfc_type-nppi_cnum-14_cname-rew-pun_F-S (Age Negative; Slide 81)
# mask-rtpj_type-ppi_seed-VS_cnum-14_cname-rew-pun_F-S (Age X Ratings Interaction Negative; slide 71)
# mask-mtg_type-act_cnum-17_cname-rew_F-S.txt (Age Positive; slide 87 and 91)

```


### 2.1 Read Data

```{r import-data}

# Read the combined CSV file
df <- read.csv("extractions-retest-copy.csv")

```

```{r}

# Create Dave's 1/var(s) column
df$`weights_dlpfc_type.nppi_cnum.14_cname.rew.pun_F.S` <- 1 / df$`var_mask.dlpfc_type.nppi_cnum.14_cname.rew.pun_F.S`

model2 <- lm(`mask.dlpfc_type.nppi_cnum.14_cname.rew.pun_F.S` ~ age_demeaned + sex + avg_tsnr_demeaned + avg_fdmean_demeaned + flip_demeaned + study_demeaned, data = df, weights = `weights_dlpfc_type.nppi_cnum.14_cname.rew.pun_F.S`)

summary(model2)


## Standard Regression Plot

ggplot(
  df,
  aes(
    x = age_demeaned,
    y = `mask.dlpfc_type.nppi_cnum.14_cname.rew.pun_F.S`)
) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = TRUE) +
  theme_minimal() +
  labs(
    x = "Age (demeaned)",
    y = "DLPFC NPPI (Rew > Pun)",
    title = "Linear Regression of DLPFC NPPI on Age"
  )

# Partial Residuals Plot

df$partial_age <- residuals(model2) +
  coef(model2)["age_demeaned"] * df$age_demeaned

ggplot(df, aes(
  x = age_demeaned,
  y = partial_age,
  weight = `weights_dlpfc_type.nppi_cnum.14_cname.rew.pun_F.S`
)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = TRUE) +
  theme_minimal() +
  labs(
    x = "Age (demeaned)",
    y = "Partial residuals (DLPFC NPPI)",
    title = "Covariate-adjusted effect of age on DLPFC NPPI"
  )


```

