---
title: "layered_plot"
author: "Jen Yang"
date: "2024-7-17"
output: html_document
---

```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

```{r restart R session, include=FALSE, results='hide'}
# .rs.restartR()
```
# Load libraries
```{r libraries, message=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(ggtext)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
# library(raincloudplots)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(RColorBrewer)
library(svglite)
library(latex2exp)
library(stringr)
library(data.table)
```

# Global chunk setting
```{r chunkGlobal, include=FALSE}
# global chunk setting
knitr::opts_chunk$set(message=FALSE, warning=FALSE, cache = FALSE)
```

# load lists
```{r}
data_dir = "/Users/Momocco/Documents/GitHub/sharedreward-aging/code"
L3_sublist_name = "L3_n124_sub.csv"
SRNDNA_sub_name = "SRNDNA_sub_demo.csv"
RF1_sub_name = "RF1_sub_demo.csv"
```

# extract final sub list
```{r}
L3_sublist_df = read.csv(paste(data_dir, L3_sublist_name, sep = "/"), header = T)
sub_all <- str_match(L3_sublist_df$L3_sub, "sub-\\s*(.*?)\\s*/L") %>% 
  as.data.frame() %>% select(V2) %>% mutate(V2 = as.numeric(V2)) %>% 
  mutate(data_source = case_when(V2 < 1000 ~ "SRNDNA",
                                 V2 > 1000 ~ "RF1"))
```

# extract demo
```{r}
SRNDNA_sub_demo = read.csv(paste(data_dir, SRNDNA_sub_name, sep = "/"), header = T) %>% 
  select(-group)
SRNDNA_sublist = SRNDNA_sub_demo$participant_id %>% str_replace("sub-", "") %>% as.numeric()
SRNDNA_sub_demo$sub_id = SRNDNA_sublist
SRNDNA_sub_demo = SRNDNA_sub_demo %>% select(-participant_id)
setnames(SRNDNA_sub_demo, "oldName", "newName")

RF1_sub_demo = read.csv(paste(data_dir, RF1_sub_name, sep = "/"), header = T) %>% 
  select(sub_id, sub_gender, sub_age)

setnames(RF1_sub_demo, colnames("sub_gender", "sub_age"), c("gender", "age"))


```

